version: "3.8"

services:
  infrared:
    image: haveachin/infrared:latest
    container_name: infrared
    restart: always
    ports:
      - 25565:25565/tcp
    volumes:
      - ./data/infrared:/etc/infrared
