# Make sure to check the documentation at https://goreleaser.com

version: 1

env:
  - REPO_URL=https://github.com/haveachin/infrared
  - DOCKER_IMAGE_NAME=haveachin/infrared

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/infrared
    env:
      - CGO_ENABLED=0
    binary: infrared
    goos:
      - linux
      - windows
      - darwin

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip

dockers:
  - image_templates:
      - "docker.io/{{ .Env.DOCKER_IMAGE_NAME }}:{{ .Version }}-amd64"
      - "docker.io/{{ .Env.DOCKER_IMAGE_NAME }}:latest-amd64"
      - "ghcr.io/{{ .Env.DOCKER_IMAGE_NAME }}:{{ .Version }}-amd64"
      - "ghcr.io/{{ .Env.DOCKER_IMAGE_NAME }}:latest-amd64"
    use: buildx
    dockerfile: build/packages/Dockerfile.goreleaser
    build_flag_templates:
      - "--pull"
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.source={{ .Env.REPO_URL }}"
  - image_templates:
      - "docker.io/{{ .Env.DOCKER_IMAGE_NAME }}:{{ .Version }}-arm64v8"
      - "docker.io/{{ .Env.DOCKER_IMAGE_NAME }}:latest-arm64v8"
      - "ghcr.io/{{ .Env.DOCKER_IMAGE_NAME }}:{{ .Version }}-arm64v8"
      - "ghcr.io/{{ .Env.DOCKER_IMAGE_NAME }}:latest-arm64v8"
    use: buildx
    goarch: arm64
    dockerfile: build/packages/Dockerfile.goreleaser
    build_flag_templates:
      - "--pull"
      - "--platform=linux/arm64/v8"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.source={{ .Env.REPO_URL }}"

docker_manifests:
  - name_template: "{{ .Env.DOCKER_IMAGE_NAME }}:{{ .Version }}"
    image_templates:
      - "{{ .Env.DOCKER_IMAGE_NAME }}:{{ .Version }}-amd64"
      - "{{ .Env.DOCKER_IMAGE_NAME }}:{{ .Version }}-arm64v8"
  - name_template: "{{ .Env.DOCKER_IMAGE_NAME }}:latest"
    image_templates:
      - "{{ .Env.DOCKER_IMAGE_NAME }}:latest-amd64"
      - "{{ .Env.DOCKER_IMAGE_NAME }}:latest-arm64v8"
  - name_template: "ghcr.io/{{ .Env.DOCKER_IMAGE_NAME }}:{{ .Version }}"
    image_templates:
      - "ghcr.io/{{ .Env.DOCKER_IMAGE_NAME }}:{{ .Version }}-amd64"
      - "ghcr.io/{{ .Env.DOCKER_IMAGE_NAME }}:{{ .Version }}-arm64v8"
  - name_template: "ghcr.io/{{ .Env.DOCKER_IMAGE_NAME }}:latest"
    image_templates:
      - "ghcr.io/{{ .Env.DOCKER_IMAGE_NAME }}:latest-amd64"
      - "ghcr.io/{{ .Env.DOCKER_IMAGE_NAME }}:latest-arm64v8"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
