{
 "title": "infrared",
 "tags": [ "linux" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values({job=\"infrared\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Individual", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Players",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(infrared_connected{instance=\"$instance\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(avg_over_time(infrared_connected{instance=\"$instance\"}[${__range_s}s]))",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Player Distribution",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 13, "w": 5, "x": 4, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by (host)(infrared_connected{instance=\"$instance\"})",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Players",
   "type": "graph",
   "gridPos": { "h": 13, "w": 15, "x": 9, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (host)(infrared_connected{instance=\"$instance\"})",
     "legendFormat": "{{host}}"
    },
    { "expr": "sum(infrared_connected)", "legendFormat": "Total" }
   ]
  },
  {
   "title": "Proxies",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(infrared_proxies{instance=\"$instance\"})"
    }
   ]
  },
  { "title": "Global", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Total Proxies",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(infrared_proxies)" }
   ]
  },
  {
   "title": "Total Players",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 3, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(infrared_connected)", "legendFormat": "Total" },
    {
     "expr": "sum(avg_over_time(infrared_connected[${__range_s}s]))",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Total Players",
   "type": "graph",
   "gridPos": { "h": 21, "w": 15, "x": 9, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (host)(infrared_connected)",
     "legendFormat": " {{host}}"
    },
    { "expr": "sum(infrared_connected)", "legendFormat": "Total" }
   ]
  },
  {
   "title": "Player Distribution",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 14, "w": 5, "x": 0, "y": 22 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by (host)(infrared_connected)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Instance Distribution",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 14, "w": 4, "x": 5, "y": 22 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by (instance)(infrared_connected)",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}